# A base image that connects a stdio program to a unix socket
ARG BASE
# Build deps: latest socat, tini and nc, in static linkage
FROM alpine as build
ARG SOCAT_VERSION=1.8.0.3
ARG SOCAT_SHA256=a9f9eb6cfb9aa6b1b4b8fe260edbac3f2c743f294db1e362b932eb3feca37ba4

RUN --mount=type=cache,target=/var/cache/apk,id=apk \
    apk add gcc g++ coreutils automake make cmake

ENV LDFLAGS=-static

ADD --checksum=sha256:${SOCAT_SHA256} \
    http://www.dest-unreach.org/socat/download/socat-${SOCAT_VERSION}.tar.gz /build-socat/src.tar.gz

RUN cd /build-socat && tar -xf src.tar.gz && cd socat-${SOCAT_VERSION} && \
    ./configure --prefix=/usr/local && make && make install

ADD https://github.com/krallin/tini/archive/refs/heads/master.zip /build-tini/src.zip

RUN cd /build-tini && unzip src.zip && cd tini-master && \
    cmake -S . -B build && cmake --build build --target install

FROM ${BASE}
ARG BASE_CMD
ARG SOCKET_PATH=/socket

# Install utils
COPY --chmod=0755 --from=build /usr/local/bin/socat /usr/local/bin/tini /usr/local/bin

ENV STDIO_BASE_CMD="${BASE_CMD}"

ENV UNIX_SOCKET_PATH="${SOCKET_PATH}"

COPY --chmod=0755 entrypoint-socat.sh /

ENTRYPOINT ["tini", "--", "/entrypoint-socat.sh"]
CMD []