# Host-specific configuration stage, adds configuration only
# Assuming we are building from ../arch-base, but this could be overridden
FROM bootc-arch-base

# Add additional host-specific packages from build context, if any
RUN --mount=type=bind,target=/tmp \
    --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    [ -f /tmp/PKGS ] && { pacman -Syy - --noconfirm --needed </tmp/PKGS; } || exit 0

# Adding layer
COPY rootfs /

RUN --mount=type=secret,id=creds \
    chpasswd < /run/secrets/creds

# Run setup script from build context, if any
RUN --mount=type=bind,target=/tmp \
    [ -f /tmp/setup.sh ] && bash /tmp/setup.sh || exit 0