# Host-specific configuration stage, adds configuration only
# Assuming we are building from ../arch-base, but this could be overridden
FROM bootc-arch-base

# Add additional host-specific packages from build context, if any
RUN --mount=type=bind,target=/tmp \
    [ -f /tmp/PKGS ] && { pacman -Sy - --noconfirm --needed </tmp/PKGS && pacman -Scc --noconfirm; } || exit 0

# Adding layer
COPY rootfs /

# Run setup script from build context, if any
RUN --mount=type=bind,target=/tmp \
    [ -f /tmp/setup.sh ] && bash /tmp/setup.sh || exit 0