ARG NIXPKGS_VERSION=nixos-25.11
FROM ghcr.io/nix-community/docker-nixpkgs/nix-flakes:${NIXPKGS_VERSION}-x86_64-linux as nix-static

RUN nix build nixpkgs#nixStatic

RUN cp /result/bin/nix /nixStatic

# From ../arch-base
# Image that contains common configurations that are shared between hosts
FROM bootc-arch-base

RUN --mount=type=bind,from=nix-static,target=/var/mnt \
    install -m0755 /var/mnt/nixStatic /usr/bin

COPY rootfs /