FROM ghcr.io/astral-sh/uv:python3.12-bookworm

RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    uv venv /venv && . /venv/bin/activate && \
    uv pip install torch torchvision torchaudio --index-url=https://download.pytorch.org/whl/cu128

ENTRYPOINT ["/venv/bin/python3"]