# From ../arch-base
ARG BASE=bootc-arch-base

FROM ${BASE}
ARG K0S_VERSION="v1.34.2+k0s.0"

ADD --chmod=0755 "https://github.com/k0sproject/k0s/releases/download/${K0S_VERSION}/k0s-${K0S_VERSION}-amd64" /usr/bin/k0s