ARG RUNTIME_TYPE=rocm

FROM pytorch-${RUNTIME_TYPE}-venv

ARG RUNTIME_TYPE
ARG RUNTIME_VERSION=6.4

RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    curl https://raw.githubusercontent.com/comfyanonymous/ComfyUI/refs/heads/master/requirements.txt \
        -o /tmp/comfyui-deps.txt &&  . /venv/bin/activate && \
        uv pip install -r /tmp/comfyui-deps.txt \
            --extra-index-url https://download.pytorch.org/whl/${RUNTIME_TYPE}${RUNTIME_VERSION} && \
        mkdir /app && chown 1000:1000 -R /venv

# Install dependencies for various accelerated algorithms

# For ComfyUI-Manager to manage custom nodes dependencies
RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    . /venv/bin/activate && uv pip install pip uv

# Other external dependencies required by various custom nodes
RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update && apt-get install -y cmake libgl1 ffmpeg

ENV HOME=/app

USER 1000:1000

ENTRYPOINT ["/app/entrypoint.sh"]

EXPOSE 8188/tcp