FROM scratch as dep-files

ADD https://raw.githubusercontent.com/comfyanonymous/ComfyUI/refs/heads/master/requirements.txt /comfyui-deps.txt

ADD https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/refs/heads/main/requirements.txt /comfyui-manager-deps.txt

FROM ghcr.io/astral-sh/uv:python3.13-trixie
ARG RUNTIME_TYPE=rocm

RUN uv venv /venv

ENV VIRTUAL_ENV=/venv

RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    --mount=from=dep-files,target=/mnt/dep-files \
    [ ${RUNTIME_TYPE} = rocm ] && index_url="https://download.pytorch.org/whl/rocm7.1"; \
    [ ${RUNTIME_TYPE} = cu ] && index_url="https://download.pytorch.org/whl/cu130"; \
    uv pip install -r /mnt/dep-files/comfyui-deps.txt \
        --extra-index-url \$index_url && \
    uv pip install -r /mnt/dep-files/comfyui-manager-deps.txt \
        --extra-index-url \$index_url

# Install dependencies for various accelerated algorithms
# flash attention
RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    [ ${RUNTIME_TYPE} = rocm ] || exit 0; \
    uv pip install flash-attn --no-build-isolation

# sage attention
RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    [ ${RUNTIME_TYPE} = rocm ] || exit 0; \
    uv pip install sageattention==2.2.0 --no-build-isolation

# For ComfyUI-Manager to manage custom nodes dependencies
RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    uv pip install pip uv

# Other external dependencies required by various custom nodes
RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update && apt-get install -y cmake libgl1 ffmpeg

# tini Init proxy
RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    apt-get update && apt-get install -y tini

ENV HOME=/app

ENTRYPOINT ["tini", "--"]

CMD ["/app/entrypoint.sh"]

EXPOSE 8188/tcp