# Build Stage
ARG CUDA_VERSION=12.8.1
FROM nvidia/cuda:${CUDA_VERSION}-cudnn-devel-ubuntu24.04 AS build
ARG PYTHON_VERSION=3.12.3
ARG TORCH_VERSION=2.8.0

RUN --mount=type=cache,target=/var/cache/apt,id=apt \
    --mount=type=cache,target=/root/.cache/pip,id=pip \
    apt-get update && apt-get install -y python3-pip ninja-build && pip install uv --break-system-packages

RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    uv venv -p ${PYTHON_VERSION} /venv && . /venv/bin/activate && uv pip install pip setuptools wheel packaging

RUN --mount=type=cache,target=/root/.cache/uv,id=uv \
    . /venv/bin/activate && uv --no-cache pip install torch==${TORCH_VERSION}

COPY vendor/Block-Sparse-SageAttention-2.0 /build

ENV TORCH_CUDA_ARCH_LIST="8.6;8.9;9.0;12.0+PTX"

WORKDIR /build

RUN . /venv/bin/activate && pip wheel .

RUN mv /build/*.whl /

# Storage stage
FROM scratch

COPY --from=build /*.whl /
