# This image is for building AUR packages for consumption by other archlinux images
FROM docker.io/archlinux/archlinux

RUN pacman -Sy --needed --noconfirm git base-devel && \
    pacman -Scc --noconfirm

RUN useradd -m -d /var/build -g wheel builder && \
    chmod 755 /var/build && \
    echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER builder

WORKDIR /var/build

RUN git clone https://aur.archlinux.org/aurutils.git && cd aurutils && \
    makepkg -si --noconfirm

RUN printf '[sitepkgs]\nSigLevel = Never\nServer = file:///var/build/repo/\n' | sudo tee -a /etc/pacman.conf && \
    mkdir /var/build/repo && repo-add /var/build/repo/sitepkgs.db.tar.gz && sudo pacman -Sy --noconfirm

# To use builder, build needed AUR packages by
# RUN aur sync -n --noview <pkgs>

# To install built image to another archlinux image
# RUN cp -f /etc/pacman.conf /etc/pacman-local-repo.conf && \ 
#    printf '[sitepkgs]\nSigLevel = Never\nServer = file:///var/local-repo/\n' | sudo tee -a /etc/pacman-local-repo.conf
# RUN --mount=type=bind,from=arch-aur-builder,source=/var/build/repo,target=/var/local-repo \
#   pacman -Sy --config /etc/pacman-local-repo.conf --needed --noconfirm <pkgs> && pacman -Scc --noconfirm
