FROM docker.io/archlinux/archlinux as yay-base

RUN printf '[archlinuxcn]\nServer = https://repo.archlinuxcn.org/$arch\n' >> /etc/pacman.conf

# Remove all thinning options in pacman.conf, these are designed for service containers but we are not
# Note that /etc/machine-id needs to be added if this is done
# This WILL be handled if image is eventually consumed by distrobox/bootc
# and we don't need to do anything about it
RUN sed -i 's/^NoExtract *=.*$//g' /etc/pacman.conf

# Reinstall everything to obtain the thinned files of default packages
# This effectively updates everything as well so we update keyring alongside
RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman-key --init && pacman -Sy && \
    pacman -S archlinux-keyring archlinuxcn-keyring --noconfirm && \
    pacman -Qq | pacman -S --noconfirm -

RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman -S --needed --noconfirm yay base-devel

# From ../../base/arch-aur-builder
FROM arch-aur-builder as aur-builder

RUN aur sync -n --noview bindfs

FROM yay-base

RUN cp -f /etc/pacman.conf /etc/pacman-local-repo.conf && \ 
    printf '[sitepkgs]\nSigLevel = Never\nServer = file:///var/local-repo/\n' | sudo tee -a /etc/pacman-local-repo.conf

# Install AUR packages built previously
RUN --mount=type=tmpfs,target=/var/lib/pacman/sync \
    --mount=type=tmpfs,target=/var/cache/pacman/pkg \
    --mount=type=bind,from=aur-builder,source=/var/build/repo,target=/var/local-repo \
    pacman -Sy --config /etc/pacman-local-repo.conf --needed --noconfirm bindfs

# Pre-install packages installed by distrobox-init, to speed up init process in distrobox
RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman -S --needed --noconfirm zsh bash-completion bc curl diffutils findutils glibc gnupg \
    iputils inetutils keyutils less lsof man-db man-pages mlocate mtr ncurses nss-mdns openssh \
    pigz pinentry procps-ng rsync shadow sudo tcpdump time traceroute tree tzdata unzip \
    util-linux util-linux-libs vte-common wget words xorg-xauth zip mesa vulkan-intel vulkan-radeon

# Customized packages
RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman -S --needed --noconfirm bubblewrap

# locale-gen
RUN sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen

# Other global settings
RUN sed -i 's/#user_allow_other/user_allow_other/' /etc/fuse.conf

