FROM alpine

RUN --mount=type=cache,target=/var/cache/apk,id=apk \
    apk add --update distcc gcc clang21

ENTRYPOINT ["/usr/bin/distccd", "--daemon", "--no-detach", "--log-stderr"]

USER 1000

EXPOSE 3632/tcp