FROM ghcr.io/astral-sh/uv:python3.12-bookworm

RUN uv venv /venv && . /venv/bin/activate && \
    uv pip install torch torchvision torchaudio --index-url=https://download.pytorch.org/whl/rocm6.4 && uv cache clean

ENTRYPOINT ["/venv/bin/python3"]