FROM ghcr.io/astral-sh/uv:python3.12-bookworm

RUN uv pip install --system torch torchvision torchaudio --index-url=https://download.pytorch.org/whl/rocm6.4 && uv cache clean

ENTRYPOINT ["/usr/local/bin/python3"]