FROM pytorch/pytorch:2.8.0-cuda12.8-cudnn9-devel

RUN apt-get update && apt-get install -y git && \
    git clone https://github.com/thu-ml/SageAttention.git /build

WORKDIR /build

ENV EXT_PARALLEL=4 NVCC_APPEND_FLAGS="--threads 8" MAX_JOBS=32

RUN pip wheel .