# Overwrite-able bootc base, in case ghcr CI version is stale
ARG BOOTC_BASE=ghcr.io/bootcrew/arch-bootc:latest
# From ../arch-base
FROM bootc-arch-base as builder

RUN pacman -Sy git kexec-tools --needed --noconfirm && pacman -Scc --noconfirm

FROM builder as initramfs-build

RUN git clone https://github.com/chaserhkj/bootc-live /work
WORKDIR /work

RUN for mod in /work/modules.d/* ; do ln -s $mod /usr/lib/dracut/modules.d; done;
RUN /bin/sh for-container.sh build-initrd-all-mods

FROM ${BOOTC_BASE}

RUN --mount=type=bind,from=initramfs-build,target=/tmp \
    cp -f /tmp/work/initrd-all-mods.img /usr/lib/modules/*/initramfs.img

RUN pacman -Sy --needed --noconfirm sudo vim bash-completion && pacman -Scc --noconfirm

# Create a user "liveuser" without password, and configure sudo for it
RUN useradd -m liveuser && passwd -d liveuser && \
    echo 'liveuser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/99_liveuser

# Wireless connection manager
RUN pacman -Sy --needed --noconfirm iwd && pacman -Scc --noconfirm

# Tools associated with installation tasks
RUN pacman -Sy --needed --noconfirm efibootmgr gptfdisk parted ddrescue && pacman -Scc --noconfirm

# Layering other live-system-specific configurations
COPY rootfs /