# Overwrite-able bootc base, in case ghcr CI version is stale
ARG BOOTC_BASE=ghcr.io/bootcrew/arch-bootc:latest
# From ../arch-base
FROM bootc-arch-base as builder

RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Syy git kexec-tools --needed --noconfirm

FROM builder as initramfs-build

RUN git clone https://github.com/chaserhkj/bootc-live /work
WORKDIR /work

RUN for mod in /work/modules.d/* ; do ln -s $mod /usr/lib/dracut/modules.d; done;
RUN /bin/sh for-container.sh build-initrd-all-mods

# Build forked cfsctl
FROM docker.io/archlinux/archlinux as cfsctl

RUN --mount=type=cache,target=/var/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/var/cache/pacman/pkg,id=pacman-cache \
    pacman -Syy --noconfirm rust git make

RUN git clone https://github.com/chaserhkj/composefs-rs /work

WORKDIR /work

RUN cargo build --release -p cfsctl && cp target/release/cfsctl /cfsctl


FROM ${BOOTC_BASE}

RUN --mount=type=bind,from=initramfs-build,target=/tmp \
    cp -f /tmp/work/initrd-all-mods.img /usr/lib/modules/*/initramfs.img

# Common tools, including tools that might be needed to work with bootc
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Syy --needed --noconfirm sudo vim bash-completion less jq fsverity-utils

# Create a user "liveuser" without password, and configure sudo for it
RUN useradd -m liveuser && passwd -d liveuser && \
    echo 'liveuser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/99_liveuser

# Wireless connection manager
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Syy --needed --noconfirm iwd

# Tools associated with installation tasks
RUN --mount=type=cache,target=/usr/lib/sysimage/lib/pacman/sync,id=pacman-sync \
    --mount=type=cache,target=/usr/lib/sysimage/cache/pacman/pkg,id=pacman-cache \
    pacman -Syy --needed --noconfirm efibootmgr gptfdisk parted ddrescue

# Install cfsctl
COPY --from=cfsctl /cfsctl /usr/bin

# Install bootc-cfsctl-cleanup
ADD --chmod=0755 \
    https://gist.githubusercontent.com/chaserhkj/ad666a558800abeae9bc51202ad0da78/raw/c30f1ad29f616bb660a163570a6766e3df866078/bootc-cfsctl-cleanup \
    /usr/bin/bootc-cfsctl-cleanup

# Layering other live-system-specific configurations
COPY rootfs /