FROM ghcr.io/astral-sh/uv:python3.12-bookworm

RUN apt-get update && apt-get install -y podman && \
    mkdir -p /etc/containers/containers.conf.d && \
    echo "[engine]" > /etc/containers/containers.conf.d/host.conf && \
    echo "remote = true" >> /etc/containers/containers.conf.d/host.conf

ENTRYPOINT ["/usr/local/bin/uv"]